# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: KeepAlive.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'KeepAlive.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Common_pb2 as Common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fKeepAlive.proto\x12\tKeepAlive\x1a\x0c\x43ommon.proto\"\x13\n\x03\x43\x32S\x12\x0c\n\x04time\x18\x01 \x02(\x03\"\x13\n\x03S2C\x12\x0c\n\x04time\x18\x01 \x02(\x03\"&\n\x07Request\x12\x1b\n\x03\x63\x32s\x18\x01 \x02(\x0b\x32\x0e.KeepAlive.C2S\"_\n\x08Response\x12\x15\n\x07retType\x18\x01 \x02(\x05:\x04-400\x12\x0e\n\x06retMsg\x18\x02 \x01(\t\x12\x0f\n\x07\x65rrCode\x18\x03 \x01(\x05\x12\x1b\n\x03s2c\x18\x04 \x01(\x0b\x32\x0e.KeepAlive.S2CB@\n\x13\x63om.futu.openapi.pbZ)github.com/futuopen/ftapi4go/pb/keepalive')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'KeepAlive_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\023com.futu.openapi.pbZ)github.com/futuopen/ftapi4go/pb/keepalive'
  _globals['_C2S']._serialized_start=44
  _globals['_C2S']._serialized_end=63
  _globals['_S2C']._serialized_start=65
  _globals['_S2C']._serialized_end=84
  _globals['_REQUEST']._serialized_start=86
  _globals['_REQUEST']._serialized_end=124
  _globals['_RESPONSE']._serialized_start=126
  _globals['_RESPONSE']._serialized_end=221
# @@protoc_insertion_point(module_scope)
