# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Qot_RequestTradeDate.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'Qot_RequestTradeDate.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Common_pb2 as Common__pb2
import Qot_Common_pb2 as Qot__Common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aQot_RequestTradeDate.proto\x12\x14Qot_RequestTradeDate\x1a\x0c\x43ommon.proto\x1a\x10Qot_Common.proto\"a\n\x03\x43\x32S\x12\x0e\n\x06market\x18\x01 \x02(\x05\x12\x11\n\tbeginTime\x18\x02 \x02(\t\x12\x0f\n\x07\x65ndTime\x18\x03 \x02(\t\x12&\n\x08security\x18\x04 \x01(\x0b\x32\x14.Qot_Common.Security\"C\n\tTradeDate\x12\x0c\n\x04time\x18\x01 \x02(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x01\x12\x15\n\rtradeDateType\x18\x03 \x01(\x05\"=\n\x03S2C\x12\x36\n\rtradeDateList\x18\x01 \x03(\x0b\x32\x1f.Qot_RequestTradeDate.TradeDate\"1\n\x07Request\x12&\n\x03\x63\x32s\x18\x01 \x02(\x0b\x32\x19.Qot_RequestTradeDate.C2S\"j\n\x08Response\x12\x15\n\x07retType\x18\x01 \x02(\x05:\x04-400\x12\x0e\n\x06retMsg\x18\x02 \x01(\t\x12\x0f\n\x07\x65rrCode\x18\x03 \x01(\x05\x12&\n\x03s2c\x18\x04 \x01(\x0b\x32\x19.Qot_RequestTradeDate.S2CBJ\n\x13\x63om.futu.openapi.pbZ3github.com/futuopen/ftapi4go/pb/qotrequesttradedate')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Qot_RequestTradeDate_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\023com.futu.openapi.pbZ3github.com/futuopen/ftapi4go/pb/qotrequesttradedate'
  _globals['_C2S']._serialized_start=84
  _globals['_C2S']._serialized_end=181
  _globals['_TRADEDATE']._serialized_start=183
  _globals['_TRADEDATE']._serialized_end=250
  _globals['_S2C']._serialized_start=252
  _globals['_S2C']._serialized_end=313
  _globals['_REQUEST']._serialized_start=315
  _globals['_REQUEST']._serialized_end=364
  _globals['_RESPONSE']._serialized_start=366
  _globals['_RESPONSE']._serialized_end=472
# @@protoc_insertion_point(module_scope)
