# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Qot_GetOptionExpirationDate.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Common_pb2 as Common__pb2
import Qot_Common_pb2 as Qot__Common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Qot_GetOptionExpirationDate.proto',
  package='Qot_GetOptionExpirationDate',
  syntax='proto2',
  serialized_pb=_b('\n!Qot_GetOptionExpirationDate.proto\x12\x1bQot_GetOptionExpirationDate\x1a\x0c\x43ommon.proto\x1a\x10Qot_Common.proto\"C\n\x03\x43\x32S\x12#\n\x05owner\x18\x01 \x02(\x0b\x32\x14.Qot_Common.Security\x12\x17\n\x0findexOptionType\x18\x02 \x01(\x05\"t\n\x14OptionExpirationDate\x12\x12\n\nstrikeTime\x18\x01 \x01(\t\x12\x17\n\x0fstrikeTimestamp\x18\x02 \x01(\x01\x12 \n\x18optionExpiryDateDistance\x18\x03 \x02(\x05\x12\r\n\x05\x63ycle\x18\x04 \x01(\x05\"J\n\x03S2C\x12\x43\n\x08\x64\x61teList\x18\x01 \x03(\x0b\x32\x31.Qot_GetOptionExpirationDate.OptionExpirationDate\"8\n\x07Request\x12-\n\x03\x63\x32s\x18\x01 \x02(\x0b\x32 .Qot_GetOptionExpirationDate.C2S\"q\n\x08Response\x12\x15\n\x07retType\x18\x01 \x02(\x05:\x04-400\x12\x0e\n\x06retMsg\x18\x02 \x01(\t\x12\x0f\n\x07\x65rrCode\x18\x03 \x01(\x05\x12-\n\x03s2c\x18\x04 \x01(\x0b\x32 .Qot_GetOptionExpirationDate.S2CBN\n\x13\x63om.futu.openapi.pbZ7github.com/futuopen/ftapi4go/pb/getoptionexpirationdate')
  ,
  dependencies=[Common__pb2.DESCRIPTOR,Qot__Common__pb2.DESCRIPTOR,])




_C2S = _descriptor.Descriptor(
  name='C2S',
  full_name='Qot_GetOptionExpirationDate.C2S',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='owner', full_name='Qot_GetOptionExpirationDate.C2S.owner', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='indexOptionType', full_name='Qot_GetOptionExpirationDate.C2S.indexOptionType', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=98,
  serialized_end=165,
)


_OPTIONEXPIRATIONDATE = _descriptor.Descriptor(
  name='OptionExpirationDate',
  full_name='Qot_GetOptionExpirationDate.OptionExpirationDate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='strikeTime', full_name='Qot_GetOptionExpirationDate.OptionExpirationDate.strikeTime', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='strikeTimestamp', full_name='Qot_GetOptionExpirationDate.OptionExpirationDate.strikeTimestamp', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='optionExpiryDateDistance', full_name='Qot_GetOptionExpirationDate.OptionExpirationDate.optionExpiryDateDistance', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cycle', full_name='Qot_GetOptionExpirationDate.OptionExpirationDate.cycle', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=167,
  serialized_end=283,
)


_S2C = _descriptor.Descriptor(
  name='S2C',
  full_name='Qot_GetOptionExpirationDate.S2C',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dateList', full_name='Qot_GetOptionExpirationDate.S2C.dateList', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=285,
  serialized_end=359,
)


_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='Qot_GetOptionExpirationDate.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='c2s', full_name='Qot_GetOptionExpirationDate.Request.c2s', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=361,
  serialized_end=417,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='Qot_GetOptionExpirationDate.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='retType', full_name='Qot_GetOptionExpirationDate.Response.retType', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=True, default_value=-400,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='retMsg', full_name='Qot_GetOptionExpirationDate.Response.retMsg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='errCode', full_name='Qot_GetOptionExpirationDate.Response.errCode', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='s2c', full_name='Qot_GetOptionExpirationDate.Response.s2c', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=419,
  serialized_end=532,
)

_C2S.fields_by_name['owner'].message_type = Qot__Common__pb2._SECURITY
_S2C.fields_by_name['dateList'].message_type = _OPTIONEXPIRATIONDATE
_REQUEST.fields_by_name['c2s'].message_type = _C2S
_RESPONSE.fields_by_name['s2c'].message_type = _S2C
DESCRIPTOR.message_types_by_name['C2S'] = _C2S
DESCRIPTOR.message_types_by_name['OptionExpirationDate'] = _OPTIONEXPIRATIONDATE
DESCRIPTOR.message_types_by_name['S2C'] = _S2C
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

C2S = _reflection.GeneratedProtocolMessageType('C2S', (_message.Message,), dict(
  DESCRIPTOR = _C2S,
  __module__ = 'Qot_GetOptionExpirationDate_pb2'
  # @@protoc_insertion_point(class_scope:Qot_GetOptionExpirationDate.C2S)
  ))
_sym_db.RegisterMessage(C2S)

OptionExpirationDate = _reflection.GeneratedProtocolMessageType('OptionExpirationDate', (_message.Message,), dict(
  DESCRIPTOR = _OPTIONEXPIRATIONDATE,
  __module__ = 'Qot_GetOptionExpirationDate_pb2'
  # @@protoc_insertion_point(class_scope:Qot_GetOptionExpirationDate.OptionExpirationDate)
  ))
_sym_db.RegisterMessage(OptionExpirationDate)

S2C = _reflection.GeneratedProtocolMessageType('S2C', (_message.Message,), dict(
  DESCRIPTOR = _S2C,
  __module__ = 'Qot_GetOptionExpirationDate_pb2'
  # @@protoc_insertion_point(class_scope:Qot_GetOptionExpirationDate.S2C)
  ))
_sym_db.RegisterMessage(S2C)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), dict(
  DESCRIPTOR = _REQUEST,
  __module__ = 'Qot_GetOptionExpirationDate_pb2'
  # @@protoc_insertion_point(class_scope:Qot_GetOptionExpirationDate.Request)
  ))
_sym_db.RegisterMessage(Request)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSE,
  __module__ = 'Qot_GetOptionExpirationDate_pb2'
  # @@protoc_insertion_point(class_scope:Qot_GetOptionExpirationDate.Response)
  ))
_sym_db.RegisterMessage(Response)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\023com.futu.openapi.pbZ7github.com/futuopen/ftapi4go/pb/getoptionexpirationdate'))
# @@protoc_insertion_point(module_scope)
