# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Qot_GetStaticInfo.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'Qot_GetStaticInfo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Common_pb2 as Common__pb2
import Qot_Common_pb2 as Qot__Common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17Qot_GetStaticInfo.proto\x12\x11Qot_GetStaticInfo\x1a\x0c\x43ommon.proto\x1a\x10Qot_Common.proto\"R\n\x03\x43\x32S\x12\x0e\n\x06market\x18\x01 \x01(\x05\x12\x0f\n\x07secType\x18\x02 \x01(\x05\x12*\n\x0csecurityList\x18\x03 \x03(\x0b\x32\x14.Qot_Common.Security\"=\n\x03S2C\x12\x36\n\x0estaticInfoList\x18\x01 \x03(\x0b\x32\x1e.Qot_Common.SecurityStaticInfo\".\n\x07Request\x12#\n\x03\x63\x32s\x18\x01 \x02(\x0b\x32\x16.Qot_GetStaticInfo.C2S\"g\n\x08Response\x12\x15\n\x07retType\x18\x01 \x02(\x05:\x04-400\x12\x0e\n\x06retMsg\x18\x02 \x01(\t\x12\x0f\n\x07\x65rrCode\x18\x03 \x01(\x05\x12#\n\x03s2c\x18\x04 \x01(\x0b\x32\x16.Qot_GetStaticInfo.S2CBG\n\x13\x63om.futu.openapi.pbZ0github.com/futuopen/ftapi4go/pb/qotgetstaticinfo')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Qot_GetStaticInfo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\023com.futu.openapi.pbZ0github.com/futuopen/ftapi4go/pb/qotgetstaticinfo'
  _globals['_C2S']._serialized_start=78
  _globals['_C2S']._serialized_end=160
  _globals['_S2C']._serialized_start=162
  _globals['_S2C']._serialized_end=223
  _globals['_REQUEST']._serialized_start=225
  _globals['_REQUEST']._serialized_end=271
  _globals['_RESPONSE']._serialized_start=273
  _globals['_RESPONSE']._serialized_end=376
# @@protoc_insertion_point(module_scope)
