# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Qot_RegQotPush.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'Qot_RegQotPush.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Common_pb2 as Common__pb2
import Qot_Common_pb2 as Qot__Common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14Qot_RegQotPush.proto\x12\x0eQot_RegQotPush\x1a\x0c\x43ommon.proto\x1a\x10Qot_Common.proto\"\x88\x01\n\x03\x43\x32S\x12*\n\x0csecurityList\x18\x01 \x03(\x0b\x32\x14.Qot_Common.Security\x12\x13\n\x0bsubTypeList\x18\x02 \x03(\x05\x12\x15\n\rrehabTypeList\x18\x03 \x03(\x05\x12\x14\n\x0cisRegOrUnReg\x18\x04 \x02(\x08\x12\x13\n\x0bisFirstPush\x18\x05 \x01(\x08\"\x05\n\x03S2C\"+\n\x07Request\x12 \n\x03\x63\x32s\x18\x01 \x02(\x0b\x32\x13.Qot_RegQotPush.C2S\"d\n\x08Response\x12\x15\n\x07retType\x18\x01 \x02(\x05:\x04-400\x12\x0e\n\x06retMsg\x18\x02 \x01(\t\x12\x0f\n\x07\x65rrCode\x18\x03 \x01(\x05\x12 \n\x03s2c\x18\x04 \x01(\x0b\x32\x13.Qot_RegQotPush.S2CBD\n\x13\x63om.futu.openapi.pbZ-github.com/futuopen/ftapi4go/pb/qotregqotpush')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Qot_RegQotPush_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\023com.futu.openapi.pbZ-github.com/futuopen/ftapi4go/pb/qotregqotpush'
  _globals['_C2S']._serialized_start=73
  _globals['_C2S']._serialized_end=209
  _globals['_S2C']._serialized_start=211
  _globals['_S2C']._serialized_end=216
  _globals['_REQUEST']._serialized_start=218
  _globals['_REQUEST']._serialized_end=261
  _globals['_RESPONSE']._serialized_start=263
  _globals['_RESPONSE']._serialized_end=363
# @@protoc_insertion_point(module_scope)
