# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Qot_GetOptionExpirationDate.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'Qot_GetOptionExpirationDate.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Common_pb2 as Common__pb2
import Qot_Common_pb2 as Qot__Common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!Qot_GetOptionExpirationDate.proto\x12\x1bQot_GetOptionExpirationDate\x1a\x0c\x43ommon.proto\x1a\x10Qot_Common.proto\"C\n\x03\x43\x32S\x12#\n\x05owner\x18\x01 \x02(\x0b\x32\x14.Qot_Common.Security\x12\x17\n\x0findexOptionType\x18\x02 \x01(\x05\"t\n\x14OptionExpirationDate\x12\x12\n\nstrikeTime\x18\x01 \x01(\t\x12\x17\n\x0fstrikeTimestamp\x18\x02 \x01(\x01\x12 \n\x18optionExpiryDateDistance\x18\x03 \x02(\x05\x12\r\n\x05\x63ycle\x18\x04 \x01(\x05\"J\n\x03S2C\x12\x43\n\x08\x64\x61teList\x18\x01 \x03(\x0b\x32\x31.Qot_GetOptionExpirationDate.OptionExpirationDate\"8\n\x07Request\x12-\n\x03\x63\x32s\x18\x01 \x02(\x0b\x32 .Qot_GetOptionExpirationDate.C2S\"q\n\x08Response\x12\x15\n\x07retType\x18\x01 \x02(\x05:\x04-400\x12\x0e\n\x06retMsg\x18\x02 \x01(\t\x12\x0f\n\x07\x65rrCode\x18\x03 \x01(\x05\x12-\n\x03s2c\x18\x04 \x01(\x0b\x32 .Qot_GetOptionExpirationDate.S2CBN\n\x13\x63om.futu.openapi.pbZ7github.com/futuopen/ftapi4go/pb/getoptionexpirationdate')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Qot_GetOptionExpirationDate_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\023com.futu.openapi.pbZ7github.com/futuopen/ftapi4go/pb/getoptionexpirationdate'
  _globals['_C2S']._serialized_start=98
  _globals['_C2S']._serialized_end=165
  _globals['_OPTIONEXPIRATIONDATE']._serialized_start=167
  _globals['_OPTIONEXPIRATIONDATE']._serialized_end=283
  _globals['_S2C']._serialized_start=285
  _globals['_S2C']._serialized_end=359
  _globals['_REQUEST']._serialized_start=361
  _globals['_REQUEST']._serialized_end=417
  _globals['_RESPONSE']._serialized_start=419
  _globals['_RESPONSE']._serialized_end=532
# @@protoc_insertion_point(module_scope)
