# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Trd_GetMarginRatio.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'Trd_GetMarginRatio.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Trd_Common_pb2 as Trd__Common__pb2
import Qot_Common_pb2 as Qot__Common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18Trd_GetMarginRatio.proto\x12\x12Trd_GetMarginRatio\x1a\x10Trd_Common.proto\x1a\x10Qot_Common.proto\"\xc9\x02\n\x0fMarginRatioInfo\x12&\n\x08security\x18\x01 \x02(\x0b\x32\x14.Qot_Common.Security\x12\x14\n\x0cisLongPermit\x18\x02 \x01(\x08\x12\x15\n\risShortPermit\x18\x03 \x01(\x08\x12\x17\n\x0fshortPoolRemain\x18\x04 \x01(\x01\x12\x14\n\x0cshortFeeRate\x18\x05 \x01(\x01\x12\x16\n\x0e\x61lertLongRatio\x18\x06 \x01(\x01\x12\x17\n\x0f\x61lertShortRatio\x18\x07 \x01(\x01\x12\x13\n\x0bimLongRatio\x18\x08 \x01(\x01\x12\x14\n\x0cimShortRatio\x18\t \x01(\x01\x12\x14\n\x0cmcmLongRatio\x18\n \x01(\x01\x12\x15\n\rmcmShortRatio\x18\x0b \x01(\x01\x12\x13\n\x0bmmLongRatio\x18\x0c \x01(\x01\x12\x14\n\x0cmmShortRatio\x18\r \x01(\x01\"X\n\x03\x43\x32S\x12%\n\x06header\x18\x01 \x02(\x0b\x32\x15.Trd_Common.TrdHeader\x12*\n\x0csecurityList\x18\x02 \x03(\x0b\x32\x14.Qot_Common.Security\"n\n\x03S2C\x12%\n\x06header\x18\x01 \x02(\x0b\x32\x15.Trd_Common.TrdHeader\x12@\n\x13marginRatioInfoList\x18\x02 \x03(\x0b\x32#.Trd_GetMarginRatio.MarginRatioInfo\"/\n\x07Request\x12$\n\x03\x63\x32s\x18\x01 \x02(\x0b\x32\x17.Trd_GetMarginRatio.C2S\"h\n\x08Response\x12\x15\n\x07retType\x18\x01 \x02(\x05:\x04-400\x12\x0e\n\x06retMsg\x18\x02 \x01(\t\x12\x0f\n\x07\x65rrCode\x18\x03 \x01(\x05\x12$\n\x03s2c\x18\x04 \x01(\x0b\x32\x17.Trd_GetMarginRatio.S2CBH\n\x13\x63om.futu.openapi.pbZ1github.com/futuopen/ftapi4go/pb/trdgetmarginratio')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Trd_GetMarginRatio_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\023com.futu.openapi.pbZ1github.com/futuopen/ftapi4go/pb/trdgetmarginratio'
  _globals['_MARGINRATIOINFO']._serialized_start=85
  _globals['_MARGINRATIOINFO']._serialized_end=414
  _globals['_C2S']._serialized_start=416
  _globals['_C2S']._serialized_end=504
  _globals['_S2C']._serialized_start=506
  _globals['_S2C']._serialized_end=616
  _globals['_REQUEST']._serialized_start=618
  _globals['_REQUEST']._serialized_end=665
  _globals['_RESPONSE']._serialized_start=667
  _globals['_RESPONSE']._serialized_end=771
# @@protoc_insertion_point(module_scope)
