# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Trd_UpdateOrderFill.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'Trd_UpdateOrderFill.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Common_pb2 as Common__pb2
import Trd_Common_pb2 as Trd__Common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19Trd_UpdateOrderFill.proto\x12\x13Trd_UpdateOrderFill\x1a\x0c\x43ommon.proto\x1a\x10Trd_Common.proto\"V\n\x03S2C\x12%\n\x06header\x18\x01 \x02(\x0b\x32\x15.Trd_Common.TrdHeader\x12(\n\torderFill\x18\x02 \x02(\x0b\x32\x15.Trd_Common.OrderFill\"i\n\x08Response\x12\x15\n\x07retType\x18\x01 \x02(\x05:\x04-400\x12\x0e\n\x06retMsg\x18\x02 \x01(\t\x12\x0f\n\x07\x65rrCode\x18\x03 \x01(\x05\x12%\n\x03s2c\x18\x04 \x01(\x0b\x32\x18.Trd_UpdateOrderFill.S2CBI\n\x13\x63om.futu.openapi.pbZ2github.com/futuopen/ftapi4go/pb/trdupdateorderfill')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Trd_UpdateOrderFill_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\023com.futu.openapi.pbZ2github.com/futuopen/ftapi4go/pb/trdupdateorderfill'
  _globals['_S2C']._serialized_start=82
  _globals['_S2C']._serialized_end=168
  _globals['_RESPONSE']._serialized_start=170
  _globals['_RESPONSE']._serialized_end=275
# @@protoc_insertion_point(module_scope)
