# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: UsedQuota.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'UsedQuota.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fUsedQuota.proto\x12\tUsedQuota\"\x05\n\x03\x43\x32S\"7\n\x03S2C\x12\x16\n\x0eused_sub_quota\x18\x01 \x01(\x05\x12\x18\n\x10used_kline_quota\x18\x02 \x01(\x05\"&\n\x07Request\x12\x1b\n\x03\x63\x32s\x18\x01 \x02(\x0b\x32\x0e.UsedQuota.C2S\"_\n\x08Response\x12\x15\n\x07retType\x18\x01 \x02(\x05:\x04-400\x12\x0e\n\x06retMsg\x18\x02 \x01(\t\x12\x0f\n\x07\x65rrCode\x18\x03 \x01(\x05\x12\x1b\n\x03s2c\x18\x04 \x01(\x0b\x32\x0e.UsedQuota.S2CB@\n\x13\x63om.futu.openapi.pbZ)github.com/futuopen/ftapi4go/pb/usedquota')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'UsedQuota_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\023com.futu.openapi.pbZ)github.com/futuopen/ftapi4go/pb/usedquota'
  _globals['_C2S']._serialized_start=30
  _globals['_C2S']._serialized_end=35
  _globals['_S2C']._serialized_start=37
  _globals['_S2C']._serialized_end=92
  _globals['_REQUEST']._serialized_start=94
  _globals['_REQUEST']._serialized_end=132
  _globals['_RESPONSE']._serialized_start=134
  _globals['_RESPONSE']._serialized_end=229
# @@protoc_insertion_point(module_scope)
