# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Verification.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'Verification.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Common_pb2 as Common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12Verification.proto\x12\x0cVerification\x1a\x0c\x43ommon.proto\"-\n\x03\x43\x32S\x12\x0c\n\x04type\x18\x01 \x02(\x05\x12\n\n\x02op\x18\x02 \x02(\x05\x12\x0c\n\x04\x63ode\x18\x03 \x01(\t\"\x05\n\x03S2C\")\n\x07Request\x12\x1e\n\x03\x63\x32s\x18\x01 \x02(\x0b\x32\x11.Verification.C2S\"b\n\x08Response\x12\x15\n\x07retType\x18\x01 \x02(\x05:\x04-400\x12\x0e\n\x06retMsg\x18\x02 \x01(\t\x12\x0f\n\x07\x65rrCode\x18\x03 \x01(\x05\x12\x1e\n\x03s2c\x18\x04 \x01(\x0b\x32\x11.Verification.S2C*i\n\x10VerificationType\x12\x1b\n\x17VerificationType_Unknow\x10\x00\x12\x1c\n\x18VerificationType_Picture\x10\x01\x12\x1a\n\x16VerificationType_Phone\x10\x02*i\n\x0eVerificationOp\x12\x19\n\x15VerificationOp_Unknow\x10\x00\x12\x1a\n\x16VerificationOp_Request\x10\x01\x12 \n\x1cVerificationOp_InputAndLogin\x10\x02\x42\x43\n\x13\x63om.futu.openapi.pbZ,github.com/futuopen/ftapi4go/pb/verification')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Verification_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\023com.futu.openapi.pbZ,github.com/futuopen/ftapi4go/pb/verification'
  _globals['_VERIFICATIONTYPE']._serialized_start=247
  _globals['_VERIFICATIONTYPE']._serialized_end=352
  _globals['_VERIFICATIONOP']._serialized_start=354
  _globals['_VERIFICATIONOP']._serialized_end=459
  _globals['_C2S']._serialized_start=50
  _globals['_C2S']._serialized_end=95
  _globals['_S2C']._serialized_start=97
  _globals['_S2C']._serialized_end=102
  _globals['_REQUEST']._serialized_start=104
  _globals['_REQUEST']._serialized_end=145
  _globals['_RESPONSE']._serialized_start=147
  _globals['_RESPONSE']._serialized_end=245
# @@protoc_insertion_point(module_scope)
